In [1]:
import numpy as np

### 1. How to Creating a 3x3 Identity Matrix with Float Data Type?

In [2]:
a = np.identity(3, dtype=float)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2. Create a 1D Array with Random Values between 0 and 1.

In [3]:
array1 = np.random.rand(5)
array1

array([0.25059826, 0.52726427, 0.19549778, 0.54707861, 0.55307804])

### 3. Create a 2D Array with Random Integer Values.

In [4]:
array2 = np.random.randint(5, size=(2, 4))
array2

array([[4, 3, 0, 1],
       [4, 2, 4, 2]])

In [5]:
def cf(i, j):
    return np.random.randint(i, j, (2,4))

cf(1,7)

array([[4, 2, 6, 2],
       [2, 3, 3, 5]])

### 5. Reshaping a 1D Array into a 2D Array

In [6]:
a = np.array([1,2,3,4])
b=a.reshape(2,2)
b

array([[1, 2],
       [3, 4]])

### 6.How to Creating a 3x3 Array of Ones?

In [7]:
aones = np.ones((3,3))
aones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 7. How to get the common items between two pythonsNumPy? 
Input:
a = np. array ([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])
Expected Output:
array ([2, 4])

In [8]:
a = np. array ([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

### 8. From array a remove all items present in array b 
Input:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])
Expected Output:
array ([1,2,3,4]

In [9]:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])
c = np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

### 9. Limit the number of items printed in python NumPy array a to a maximum of 6 elements.
a = np. arrange (15)
Expected Output:
array ([ 0, 1, 2, ..., 12, 13, 14]

In [10]:
a = np.arange(15)
np.set_printoptions()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 10. Drop all nan values from a 1D NumPy array
Input:
np. array ([1,2,3, np.nan,5,6,7, np.nan])
Desired Output:
array ([ 1., 2., 3., 5., 6., 7.])

In [11]:
a = np. array ([1,2,3, np.nan,5,6,7, np.nan])
b = a[~np.isnan(a)]
b

array([1., 2., 3., 5., 6., 7.])

### 11. Question: Create a 1D NumPy array of the first 20 natural numbers and a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20.

In [12]:
a = np.arange(1,21)
print(a)

b = a.reshape(4,5)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### 12. Question: Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, number of dimensions, and data type. Change its data type to float64 and verify the change.

In [13]:
arr1 = np.arange(24).reshape(2,3,4)
print(arr1)
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Dimension:", arr1.ndim)
print("Data type:", arr1.dtype)
print()
float_3D = arr1.astype(float)
print(float_3D)
print("Shape:", float_3D.shape)
print("Size:", float_3D.size)
print("Dimension:", float_3D.ndim)
print("Data type:", float_3D.dtype)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)
Size: 24
Dimension: 3
Data type: int32

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
Shape: (2, 3, 4)
Size: 24
Dimension: 3
Data type: float64


### 13. Question: Reshape a 1D array of 12 elements into a 3x4 2D array and then flatten it back into a 1D array using ravel (). Verify that the flattened array matches the original.

In [14]:
c = np.arange(12).reshape(3,4)
print(c)
np.set_printoptions(threshold=0)
d = np.ravel(c)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2 ...  9 10 11]


### 14. Question: Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4, 5, 6]), perform element-wise addition, subtraction, multiplication, and division. Explain the behavior when dividing by zero.

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Divide by 0:", a/0)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Divide by 0: [inf inf inf]


C:\Users\Dell\AppData\Local\Temp\ipykernel_8452\1580672386.py:8: RuntimeWarning: divide by zero encountered in divide
  print("Divide by 0:", a/0)


### 15. Question: Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform element-wise addition using broadcasting. Explain how broadcasting rules apply in this scenario.

#### In summary, broadcasting simplifies the addition process between arrays of different shapes by expanding the smaller array's dimensions, allowing for seamless element-wise operations.

In [16]:
array_2d = np.array([[1], [2], [3]])
array_1d = np.array([4,5,6])
addition = array_2d + array_1d

print("2d_array\n", array_2d)
print("1d_array\n", array_1d)
print("Addition\n", addition)

2d_array
 [[1]
 [2]
 [3]]
1d_array
 [4 5 6]
Addition
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


### 16. Question: Generate a random 2D array of integers between 0 and 10. Use conditional operators to create a Boolean mask identifying elements greater than 5. Replace all elements greater than 5 with the value 5.

In [17]:
array = np.random.randint(0, 11, size=(4,4))
print("\nOriginal array\n", array)

mask = array > 5
print("\nBoolean masked array\n", mask)

array[mask] = 5
print("\nModified array\n", array)


Original array
 [[ 6  9  7  1]
 [ 3  9  4  4]
 [10  3  0  1]
 [ 5  8  4  6]]

Boolean masked array
 [[ True  True  True False]
 [False  True False False]
 [ True False False False]
 [False  True False  True]]

Modified array
 [[5 5 5 1]
 [3 5 4 4]
 [5 3 0 1]
 [5 5 4 5]]


### 17. Question: Given a 4x4 array of random integers, use indexing and slicing to extract:
* The entire second row
* The last column
* The subarray consisting of the first two rows and first two columns

In [18]:
array = np.random.randint(0, 11, size=(4,4))
print("\nOriginal array\n", array)

second_row = array[1, :]
print("\nSecond row\n", second_row)

last_column = array[:, -1]
print("\nLast Column\n", last_column)

subarray = array[:2, :2]
print("\nSubarray with first two rows and column\n", subarray)


Original array
 [[ 2  8  5  5]
 [ 1 10  0 10]
 [ 1  5  3  0]
 [ 2  7  6  2]]

Second row
 [ 1 10  0 10]

Last Column
 [ 5 10  0  2]

Subarray with first two rows and column
 [[ 2  8]
 [ 1 10]]


### 18. Question: Describe a practical example where NumPy can be used in EDA, AI, ML, and DL, and implement a NumPy solution for a simple task in each area.

In [19]:
# For EDA

# Simulated dataset (e.g., heights of individuals in cm)
data = np.random.randint(150, 200, size=100)  # 100 random heights
mean = np.mean(data)
std_dev = np.std(data)

print("\nMean Height:", mean)
print("\nStandard Deviation of Height:", std_dev)

# For AL

# Simulated RGB image (3D array: height x width x channels)
image = np.random.randint(0, 256, (100, 100, 3))  # Random RGB image

# Convert to grayscale using the luminosity method
gray_image = np.dot(image[...,:3], [0.2989, 0.5870, 0.1140])
print("\nGrayscale Image Shape:", gray_image.shape)

# For ML

# Simulated feature data (2D array: samples x features)
features = np.random.rand(10, 3) * 100  # 10 samples, 3 features
print("\nOriginal Features:\n", features)

# Min-max normalization
min_values = np.min(features, axis=0)
max_values = np.max(features, axis=0)
normalized_features = (features - min_values) / (max_values - min_values)

print("\nNormalized Features:\n", normalized_features)

# For DL

# Simulated input data (e.g., images, flattened)
input_data = np.random.rand(64, 64)  # Single 64x64 image

# Reshape to add a channel dimension (for example, for a CNN)
reshaped_data = input_data.reshape(1, 64, 64, 1)  # (batch_size, height, width, channels)

print("\nReshaped Data Shape:", reshaped_data.shape)


Mean Height: 173.06

Standard Deviation of Height: 13.680511686336882

Grayscale Image Shape: (100, 100)

Original Features:
 [[94.89305169 93.20374559  8.30019427]
 [49.17713917 53.98179917 34.87506231]
 [29.29715427 55.75228973 32.87364672]
 ...
 [93.06259508 34.21221064 45.21428577]
 [68.63447232 22.13892681 13.0502215 ]
 [14.72604637 63.37245604  1.98697753]]

Normalized Features:
 [[1.         1.         0.07612835]
 [0.51174298 0.44808209 0.34714397]
 [0.29941992 0.47299583 0.32673315]
 ...
 [0.98045028 0.16989115 0.45258536]
 [0.71955201 0.         0.12457004]
 [0.14379696 0.58022422 0.01174495]]

Reshaped Data Shape: (1, 64, 64, 1)


### 19. Question: Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the matrix.

In [20]:
# Step 1: Create a random 4x4 matrix
matrix = np.random.rand(4, 4)
print("Random 4x4 Matrix:\n", matrix)

# Step 2: Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

# Step 3: Verify the eigenvalues by reconstructing the matrix
# Reconstruct the matrix using the formula A = V * D * V^(-1)
# where V is the matrix of eigenvectors and D is the diagonal matrix of eigenvalues
D = np.diag(eigenvalues)  # Diagonal matrix of eigenvalues
reconstructed_matrix = eigenvectors @ D @ np.linalg.inv(eigenvectors)

print("\nReconstructed Matrix:\n", reconstructed_matrix)

# Check if the original matrix and reconstructed matrix are approximately equal
print("\nAre the original and reconstructed matrices approximately equal?", np.allclose(matrix, reconstructed_matrix))

Random 4x4 Matrix:
 [[0.59887334 0.08375421 0.27750001 0.97835596]
 [0.93247877 0.04217462 0.39276506 0.42407926]
 [0.1248982  0.99620886 0.34988518 0.30379039]
 [0.03815869 0.24716115 0.72728404 0.87872132]]

Eigenvalues:
 [ 1.84994084+0.j          0.24866188+0.62642215j  0.24866188-0.62642215j
 -0.47761015+0.j        ]

Eigenvectors:
 [[-0.52995031+0.j         -0.40816497+0.32850977j -0.40816497-0.32850977j
  -0.12945859+0.j        ]
 [-0.4937897 +0.j          0.06404736+0.43457061j  0.06404736-0.43457061j
   0.55386166+0.j        ]
 [-0.47353742+0.j          0.55479427+0.j          0.55479427-0.j
  -0.7614189 +0.j        ]
 [-0.50108553+0.j         -0.22707624-0.41613544j -0.22707624+0.41613544j
   0.31099677+0.j        ]]

Reconstructed Matrix:
 [[0.59887334-9.98129139e-17j 0.08375421-2.86943717e-17j
  0.27750001+5.27584999e-17j 0.97835596-8.73352473e-17j]
 [0.93247877-3.41738032e-17j 0.04217462-1.48918076e-17j
  0.39276506+1.69280683e-17j 0.42407926-6.49093063e-17j]
 [0.1248982 -5

### 20. Question: Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array with the original.

In [21]:
array = np.arange(27)
print("Original array:\n", array)

reshaped_array = array.reshape((3,3,3))
print("\nReshaped array:\n", reshaped_array)

flattened_array = reshaped_array.flatten()  # we can also use ravel() function instead of flatten()
print("\nFlattened array:\n", flattened_array)

comparison = np.array_equal(array, flattened_array)
print("\nComaprison of both array:", comparison)

Original array:
 [ 0  1  2 ... 24 25 26]

Reshaped array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Flattened array:
 [ 0  1  2 ... 24 25 26]

Comaprison of both array: True


### 21. Question: Perform matrix multiplication of two 2D arrays using np.dot() and @. Compare the results and performance of both methods using a large dataset.

In [26]:
import time
size = 1000
M = np.random.rand(size, size)   
N = np.random.rand(size, size)

# using dot() functiom
start_time_dot = time.time()
result_dot = np.dot(M, N)
end_time_dot = time.time()
time_dot = end_time_dot - start_time_dot

# using at@ function
start_time_at = time.time()
result_at = M @ N
end_time_at = time.time()
time_at = end_time_at - start_time_at

print(f"Matrix multiplication using np.dot() took {time_dot:.4f} seconds.")
print(f"Matrix multiplication using @ took {time_at:.4f} seconds.")

# Compare result
result_match = np.allclose(result_dot, result_at)
print(f"Ressult Match: {result_match}")

Matrix multiplication using np.dot() took 0.1191 seconds.
Matrix multiplication using @ took 0.0650 seconds.
Ressult Match: True


## 22. Question: Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4, 1). Perform an element-wise operation using broadcasting and explain the result. Use np. new axis to achieve the same result without broadcasting.

In [37]:
array_3d = np.array([[[1,2,3,4]], [[5,6,7,8]]])
array_2d = np.array([[10],[20],[30],[40]])

# Result using Broadcasting
result_broadcasting = array_3d + array_2d.T
print("Result with Broadcasting:\n", result_broadcasting)

# Result using newaxis function
array_2d_newaxis = array_2d[np.newaxis, :, :]
array_3d_newaxis = array_3d[:, :, np.newaxis]

result_nnewaxis = array_2d_newaxis + array_3d_newaxis
print("Result with newaxis:\n", result_nnewaxis)

Result with Broadcasting:
 [[[11 22 33 44]]

 [[15 26 37 48]]]
Result with newaxis:
 [[[[11 12 13 14]
   [21 22 23 24]
   [31 32 33 34]
   [41 42 43 44]]]


 [[[15 16 17 18]
   [25 26 27 28]
   [35 36 37 38]
   [45 46 47 48]]]]


## 23. Question: Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. Replace these values with their squares and leave the rest unchanged.

In [43]:
A = np.random.rand(5,5)
print("Original array:\n", A)

mask = A < 5

A[mask] = A[mask] ** 2
print("\nModified array:\n", A)

Original array:
 [[0.60622017 0.3809823  0.16606368 0.4997252  0.19004229]
 [0.35963991 0.5044158  0.8911074  0.96058811 0.90783452]
 [0.19324993 0.54836788 0.97600299 0.89358356 0.61995452]
 [0.14460818 0.41186987 0.73559798 0.49705872 0.69470997]
 [0.66659565 0.84912342 0.51541334 0.2228092  0.48349007]]

Modified array:
 [[0.3675029  0.14514751 0.02757714 0.24972527 0.03611607]
 [0.12934086 0.2544353  0.7940724  0.92272952 0.82416351]
 [0.03734554 0.30070733 0.95258184 0.79849158 0.38434361]
 [0.02091153 0.16963679 0.54110439 0.24706737 0.48262194]
 [0.44434976 0.72101058 0.26565091 0.04964394 0.23376265]]


## 24. Question: Given a 5x5 array of sequential integers, use slicing to:
* Extract the diagonal elements
* Replace the elements of the middle row with zeros
* Flip the array vertically and horizontally

In [49]:
array = np.arange(1,26).reshape(5,5)
print("Original array:\n", array)

diagonal = np.diagonal(array)
print("\nDiagonal array:\n", array)

array[2, :] = 0
print("\nArray after replacing middle row with 0:\n", array)

flip = np.flipud(np.fliplr(array))
print("\nFlippped array:\n", flip)

Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Diagonal array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array after replacing middle row with 0:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Flippped array:
 [[25 24 23 22 21]
 [20 19 18 17 16]
 [ 0  0  0  0  0]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## 25. Question: Create a 4D array of shape (2, 3, 4, 5) with random integers. Use advanced slicing to extract a subarray and compute the mean along a specified axis.

In [53]:
array_4d = np.random.randint(0, 100, size=(2,3,4,5))
print("Original array:\n", array_4d)

subarray = array_4d[0, :, -2:, :3]
print("\nExtracted Subarray:\n", subarray)

mean = np.mean(subarray, axis=1)
print("\nMean along axis:\n", mean)

Original array:
 [[[[42 44 11 80  4]
   [87 95 14 63 67]
   [ 9 25 58 43 42]
   [50 16 33  7 11]]

  [[11 37  8 97 63]
   [32 96  8  9 46]
   [11  8 34 88 41]
   [79 55 90 98 33]]

  [[30 47 15 84 84]
   [76 71 29 84  8]
   [59 89 60 62 72]
   [84 46 43 73 83]]]


 [[[16 65 47  1 94]
   [ 4 56 78 75 68]
   [36 65 54 86 37]
   [98 85 78  2  0]]

  [[63 93 86 58 43]
   [40 10 38  8 93]
   [52 31 85 46 61]
   [ 0 33 29 69 13]]

  [[27 88 94 94 66]
   [53 42 79 79 64]
   [28 11  2 12 88]
   [96  2 92 59 81]]]]

Extracted Subarray:
 [[[ 9 25 58]
  [50 16 33]]

 [[11  8 34]
  [79 55 90]]

 [[59 89 60]
  [84 46 43]]]

Mean along axis:
 [[29.5 20.5 45.5]
 [45.  31.5 62. ]
 [71.5 67.5 51.5]]


## 26. Question: Given an array of shape (10, 20), reshape it to (20, 10) and (5, 40). Discuss the impact on the array's shape, size, and dimensionality.

In [66]:
array = np.arange(200).reshape(10, 20)
print(array)

reshape1 = array.reshape(20, 10)
print("\n",reshape1)
print("\nReshaped Array (20, 10):\n", reshape1)
print("Shape:", reshape1.shape)
print("Size:", reshape1.size)
print("Dimensionality:", reshape1.ndim)

reshape2 = array.reshape(5,40)
print("\n",reshape2)
print("\nReshaped Array (5, 40):\n", reshape2)
print("Shape:", reshape2.shape)
print("Size:", reshape2.size)
print("Dimensionality:", reshape2.ndim)

[[  0   1   2 ...  17  18  19]
 [ 20  21  22 ...  37  38  39]
 [ 40  41  42 ...  57  58  59]
 ...
 [140 141 142 ... 157 158 159]
 [160 161 162 ... 177 178 179]
 [180 181 182 ... 197 198 199]]

 [[  0   1   2 ...   7   8   9]
 [ 10  11  12 ...  17  18  19]
 [ 20  21  22 ...  27  28  29]
 ...
 [170 171 172 ... 177 178 179]
 [180 181 182 ... 187 188 189]
 [190 191 192 ... 197 198 199]]

Reshaped Array (20, 10):
 [[  0   1   2 ...   7   8   9]
 [ 10  11  12 ...  17  18  19]
 [ 20  21  22 ...  27  28  29]
 ...
 [170 171 172 ... 177 178 179]
 [180 181 182 ... 187 188 189]
 [190 191 192 ... 197 198 199]]
Shape: (20, 10)
Size: 200
Dimensionality: 2

 [[  0   1   2 ...  37  38  39]
 [ 40  41  42 ...  77  78  79]
 [ 80  81  82 ... 117 118 119]
 [120 121 122 ... 157 158 159]
 [160 161 162 ... 197 198 199]]

Reshaped Array (5, 40):
 [[  0   1   2 ...  37  38  39]
 [ 40  41  42 ...  77  78  79]
 [ 80  81  82 ... 117 118 119]
 [120 121 122 ... 157 158 159]
 [160 161 162 ... 197 198 199]]
Shape: (5, 

* Reshaping an array changes its shape but not its size or dimensionality.
* The total number of elements must remain the same during reshaping.
* The ability to reshape arrays flexibly is one of the powerful features of NumPy, allowing for different views and manipulations of the same data.

## 27. Question: Generate a large 2D array and demonstrate the use of np. reshape () and unravel () to manipulate its shape for various linear algebra operations.

In [68]:
rows, cols = 1000, 1000
large_array = np.arange(rows * cols).reshape(rows, cols)

print("Original 2D Array Shape:", large_array.shape)

reshaped_array_1 = large_array.reshape((2000, 500))
reshaped_array_2 = large_array.reshape((10, 100, 1000))

print("Reshaped Array (2000, 500):", reshaped_array_1.shape)
print("Reshaped Array (10, 100, 1000):", reshaped_array_2.shape)

flattened_array = large_array.ravel()
print("Flattened Array Shape:", flattened_array.shape)

restored_array = flattened_array.reshape(rows, cols)
print("Restored Array Shape:", restored_array.shape)

matrix_1 = np.random.rand(500, 1000)
matrix_2 = np.random.rand(1000, 500)

reshaped_matrix_1 = matrix_1.reshape(1000, 500)
reshaped_matrix_2 = matrix_2.reshape(500, 1000)

result_matrix = np.dot(reshaped_matrix_1, reshaped_matrix_2)

print("Result Matrix Shape:", result_matrix.shape)

mean_value = np.mean(flattened_array)
print("Mean of the Flattened Array:", mean_value)

Original 2D Array Shape: (1000, 1000)
Reshaped Array (2000, 500): (2000, 500)
Reshaped Array (10, 100, 1000): (10, 100, 1000)
Flattened Array Shape: (1000000,)
Restored Array Shape: (1000, 1000)
Result Matrix Shape: (1000, 1000)
Mean of the Flattened Array: 499999.5


## 28. Question: Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular part to zero. Verify the result.

In [69]:
import numpy as np

# Step 1: Create a 6x6 matrix
matrix = np.random.randint(1, 10, size=(6, 6))  # Generating a 6x6 matrix with random integers
print("Original Matrix:\n", matrix)

# Step 2: Extract the upper triangular part
upper_triangular = np.triu(matrix)  # This keeps the upper triangular part and sets the lower part to zero
print("\nUpper Triangular Part:\n", upper_triangular)

# Step 3: Set the lower triangular part to zero
matrix[np.tril_indices(6, -1)] = 0  # Set lower triangular indices to zero
print("\nMatrix after setting lower triangular part to zero:\n", matrix)

# Step 4: Verify the result
print("\nVerification (should be upper triangular):")
print(matrix)

Original Matrix:
 [[4 3 6 3 8 5]
 [8 5 2 3 8 4]
 [7 8 2 5 6 7]
 [7 1 2 5 5 3]
 [5 8 7 7 4 5]
 [7 8 8 9 4 5]]

Upper Triangular Part:
 [[4 3 6 3 8 5]
 [0 5 2 3 8 4]
 [0 0 2 5 6 7]
 [0 0 0 5 5 3]
 [0 0 0 0 4 5]
 [0 0 0 0 0 5]]

Matrix after setting lower triangular part to zero:
 [[4 3 6 3 8 5]
 [0 5 2 3 8 4]
 [0 0 2 5 6 7]
 [0 0 0 5 5 3]
 [0 0 0 0 4 5]
 [0 0 0 0 0 5]]

Verification (should be upper triangular):
[[4 3 6 3 8 5]
 [0 5 2 3 8 4]
 [0 0 2 5 6 7]
 [0 0 0 5 5 3]
 [0 0 0 0 4 5]
 [0 0 0 0 0 5]]


In [71]:
# Another Method
matrix = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 Matrix:\n", matrix)

upper_triangular = np.triu(matrix)
print("Upper Triangular Part:\n", upper_triangular)

lower_triangular_zeroed = np.triu(matrix)
print("Matrix with Lower Triangular Part Set to Zero:\n", lower_triangular_zeroed)

lower_triangular_zeroed_manual = matrix.copy()
lower_triangular_zeroed_manual[np.tril_indices_from(lower_triangular_zeroed_manual, -1)] = 0
print("Manually Zeroed Lower Triangular Part Matrix:\n", lower_triangular_zeroed_manual)

print("Verification (Are the matrices equal?):", np.array_equal(lower_triangular_zeroed, lower_triangular_zeroed_manual))

Original 6x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Upper Triangular Part:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Matrix with Lower Triangular Part Set to Zero:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Manually Zeroed Lower Triangular Part Matrix:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Verification (Are the matrices equal?): True
